spring.application.name=ai-web-scraper
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}
groq.api-key=${GROQ_API_KEY:}
groq.model=${GROQ_MODEL:openai/gpt-oss-20b}
groq.base-url=https://api.groq.com/openai/v1
server.error.include-message=never
server.error.include-stacktrace=never
